# Prod Container Promote
name: Prod Container Promote
 
on:
  workflow_call:
    inputs:
      VAR_ONE:
        required: true
        type: string
      VAR_TWO:
        required: true
        type: string

permissions: read-all

# Set defaults
defaults:
  run:
    shell: bash

jobs:
  fake_deploy:
    if: ${{ github.ref == 'refs/heads/main' || github.event.release.target_commitish == 'main' }}
    name: Fake Deploy TESTING
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check SHAs
        id: check_sha
        run: | 
          export HEAD_SHA=$(git rev-parse --short=8 HEAD)
          export ECR_SHA_BAD=${{ inputs.VAR_ONE }}
          export ECR_SHA_GOOD=$(git rev-parse --short=8 HEAD)
          if [[ $HEAD_SHA == $ECR_SHA_BAD ]]; then
            echo "sha_match=true" >> $GITHUB_ENV
          else
            echo "sha_match=false" >> $GITHUB_ENV
            echo "FAILURE: Stage-Workloads SHA did not match the main branch." >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
        continue-on-error: false

      - name: Show values
        run: |
          echo ${{ inputs.VAR_ONE }}
          echo ${{ inputs.VAR_TWO }}
          echo ${{ github.ref }}
          echo ${{ github.event.release.target_commitish }}
          echo ${{ env.sha_match }}

      - name: Run On True
        if: ${{ env.sha_match == 'true'}}
        run: |
          echo "The SHAs matched! (the next line should be true)"
          echo ${{ env.sha_match}}

      - name: Run on False
        if: ${{ env.sha_match == 'false' }}
        run: |
          echo "The SHAs did NOT match (the next line should be false)"
          echo ${{ env.sha_match}}

      - name: Show GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
